version: "3.7"

services:
    server:
        build: "./server"
        command: python manage.py runserver 0.0.0.0:8000
        # volumes:
        #     - ./server/:/usr/src/server/
        ports:
            - 8000:8000
        # env_file:
        #     - ./.env.dev
    main:
        build: "./main"
        command: python -m main
        depends_on:
            - server
        devices:
            - "/dev/i2c-1:/dev/i2c-1"
        restart: on-failure
    # client:
    #     build: "./client"
    #     command: ng serve